name: update-blog
# 触发条件
on:
  push:
    branches:
      - main
jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: build
        run: |
          git clone https://github.com/zxl7/zxl7.github.io.git
          cd ./zxl7.github.io/docs/.vuepress/dist
          echo 'zxl7.top' > CNAME
          git init
          git config --global user.email "zxlcoder@gmail.com"
          git config --global user.name "zxl7"
          git add .
          git commit -m '自动更新博客文章!'
          git push -f https://github.com/zxl7/zxl7.github.io.git main:gh-pages
