# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: update-blog

# 触发条件
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
- uses:  |
        npm run build

        # 进入生成的文件夹
        cd docs/.vuepress/dist

        echo 'zxl7.top' > CNAME
        # 如果是发布到自定义域名
        git init
        git add -A
        git commit -m '自动更新博客文章~'
        git push -f git@github.com:zxl7/zxl7.github.io.git master:gh-pages