name: update-blog
# 触发条件
on:
  push:
    branches:
      - main
jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 14
      - name: build
      - run: |
          npm run build
          # 进入生成的文件夹
          cd docs/.vuepress/dist
          echo 'zxl7.top' > CNAME
          # 如果是发布到自定义域名
          git init
          git add -A
          git commit -m '自动更新博客文章~'
          git push -f git@github.com:zxl7/zxl7.github.io.git master:gh-pages
